### ISSUE TITLE
Implement mulligans

### ISSUE THREAD

**Issue by eshapiro42** [eshapiro42/dixit#10]
Allow the user to replace one card from their hand each time someone's score first hits/exceeds a multiple of thirty.

**Comment by eshapiro42** [comment]
Allowed one mulligan per turn. Will reopen if this ends up being too much.

**Comment by eshapiro42** [comment]
This is broken. The server doesn't think the mulliganed card is in the player's hand.

```
2021-05-14T23:45:34.096151+00:00 app[web.1]: Player Eric mulliganed card Crop00199.jpg
2021-05-14T23:45:34.105981+00:00 app[web.1]: [2021-05-14 23:45:34,098] ERROR in app: Exception on /api/sendMulligan [POST]
2021-05-14T23:45:34.105984+00:00 app[web.1]: Traceback (most recent call last):
2021-05-14T23:45:34.105984+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
2021-05-14T23:45:34.105985+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-05-14T23:45:34.105985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-05-14T23:45:34.105986+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-05-14T23:45:34.105986+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-05-14T23:45:34.105986+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2021-05-14T23:45:34.105987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
2021-05-14T23:45:34.105988+00:00 app[web.1]:     raise value
2021-05-14T23:45:34.105988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-05-14T23:45:34.105988+00:00 app[web.1]:     rv = self.dispatch_request()
2021-05-14T23:45:34.105989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
2021-05-14T23:45:34.105997+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2021-05-14T23:45:34.105997+00:00 app[web.1]:   File "/app/app.py", line 274, in sendMulligan
2021-05-14T23:45:34.105998+00:00 app[web.1]:     player.discard_card(card)
2021-05-14T23:45:34.105999+00:00 app[web.1]:   File "/app/game.py", line 184, in discard_card
2021-05-14T23:45:34.105999+00:00 app[web.1]:     self.hand.remove(card)
2021-05-14T23:45:34.105999+00:00 app[web.1]: ValueError: list.remove(x): x not in list
2021-05-14T23:45:34.108355+00:00 app[web.1]: 10.156.16.229 - - [14/May/2021:23:45:34 +0000] "POST /api/sendMulligan HTTP/1.1" 500 290 "https://quarantine-dixit.herokuapp.com/play" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
```
